### ISSUE TITLE
Hardware region boundary display appears to be wrong by one pixel

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#182]
When maximally zoomed in, the HW region boundary (red lines on the image display) appears to be one pixel off.  When zoomed out, the discrepancy seems to be larger. This might be a Firefly display error.

**Comment by tgoldina** [comment]
I have just updated the master branch and [firefly releases](https://github.com/Caltech-IPAC/firefly/releases) (built from master) with the newest code. The issue might have been fixed by [pr315](https://github.com/Caltech-IPAC/firefly/pull/315), which is a part of this release. Please, check it out.

**Comment by weiren2** [comment]
@tgoldina I just tried the new release and the bug seemed to be fixed. We'll do more testing on that.
