### ISSUE TITLE
Boxes should be resizable and moveable.

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#38]
Right now, they are too big.  They need to be resizable as well as moveable,  so that the user can lay out the window.

I cannot move or resize the terminal window.

Related, it would be better if the font size were a smaller fraction of the box size, to have less text wrapping.  Could this be done dynamically, as the box is resized?

Also, the last line of terminal text is partially hidden by the command entry box.

**Comment by jbpagliuco** [comment]
Making the boxes resizable is very easy, there's a jquery plugin for it.

I made it so the terminal window is always fixed in the bottom right corner with a fixed width and height. Making it resizable should be easy. Moving it would be easy as well, although I think it should be easy to anchor in the bottom right corner (snapping to it). In addition, we said it should be minimizable.

I'm not sure what you mean about the text wrapping with the boxes. The box will expand to the necessary size so each line of text fits on one line. I do however think it would be a good idea to dynamically change the font size. I was thinking each box has a settings tab for this.

I'm not sure why the terminal output area is hidden like that on the server. There's code to calculate the height of that area dynamically so it just fits, which works on my machine. I'll have to look into why that's not working on the server.

**Comment by jonthaler** [comment]
> I'm not sure what you mean about the text wrapping with the boxes. The box will expand to the necessary size so each line of text fits on one line. I do however think it would be a good idea to dynamically change the font size. I was thinking each box has a settings tab for this.

When I issue the "average_pixel" command, the box the response appears in does not resize - the text wraps.  I am using Firefox on a Mac.

**Comment by jbpagliuco** [comment]
That's actually pretty weird, on my machine, it doesn't wrap on chrome or firefox. I have a feeling using a CSS reset sheet will fix the problem. I'll try to get it in by Friday so we can see if it had any effect.

**Comment by weiren2** [comment]
The text doesn't wrap unless I put the box close to the right boundary of the screen/browser.

**Comment by weiren2** [comment]
This might be a related issue with box and terminal @jbpagliuco. If I accidentally move the box to somewhere behind the terminal, then there is no way I can drag the box back because the terminal is always on top of others. Maybe it's a good idea to restrict the regions where the boxes can be moved to.
Or there are ways to move the box back to somewhere else that I don't know.

**Comment by jonthaler** [comment]
Wei: Yes, that,s the behavior I see.  Sorry for not noticing it.  In any case, I would like more control over window (and text) sizes.  I have less screen space on my laptop, and need to be able to control the layout.

**Comment by jbpagliuco** [comment]
I split this up into several different issues, so I'm gonna close it
