### ISSUE TITLE
Default parameters

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#48]
I wrote an email about this one too. Basically we need a scheme to allow for default parameters

**Comment by jonthaler** [comment]
I agree with your "all or nothing" analysis.  Attempts to do otherwise (eg, type a period for the default) look like kludges to me.  However, I think that most of the time we will have only one viewer and one box.  It will be a significant saving to the user to simplify command entry in that situation.

**Comment by jbpagliuco** [comment]
#123
